name: PR CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre_merge_ci:
    name: "Lite CI"
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: extractions/setup-just@v1
        with:
          just-version: 1.2.0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Ensure contracts build and are formatted
        run: |
          forge build
          forge fmt --check
